# Site settings

title: Ballonni's Pizza
description: Pizzas artesanais, workshops e eventos em Portugal.
url: "https://ballonnis.com"
baseurl: ""

# Social media

twitter: "https://twitter.com/ballonnis"
facebook: "https://www.facebook.com/ballonnis"
instagram: "https://www.instagram.com/ballonnis/"
whatsapp: "https://wa.me/351925410763"

# Contacts

phone: "+351 925 410 763"
email: "geral@ballonnis.com"


# Build settings

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

